#!/usr/bin/python3
def raise_exception():
    try:
        5 / 'a'
    except (TypeError):
        pass
